### ISSUE TITLE
river_classification_metric.py update

### ISSUE THREAD

**Issue by ZahirBilal** [haugjo/float#87]
hello,

I noticed that the following lines should be modified in river_classification_metric.py as they are not anymore compatible with the current version of river. I tried to add a pull request but for some reason it does not work.

line 9 : from river.metrics import ClassificationMetric
update to: from river import metrics

line 13: def river_classification_metric(y_true: ArrayLike,
                                y_pred: ArrayLike,
                                metric: ClassificationMetric,
                                **kwargs) -> Any:

update to: def river_classification_metric(y_true: ArrayLike,
                                y_pred: ArrayLike,
                                metric: metric,
                                **kwargs) -> Any:

Best,
Zahir

**Comment by haugjo** [comment]
Hi Zahir, thanks for letting us know. I will apply the changes in the upcoming days and update the repository. We were also planing on an update of the Pypi version of float in the next couple of weeks, and will include the changes accordingly.

**Comment by haugjo** [comment]
The new version of float now properly handles river metrics. In order to use a river metric you need to
1.) Import the river metric and float river_metric-Wrapper:
```python
from river.metrics import CohenKappa
from float.prediction.evaluation.measures import river_metric
```
2.) Create a float.PredictionEvaluator and provide the corresponding `metric` parameter.
```python
evaluator = PredictionEvaluator(measure_funcs=[river_metric], metric=CohenKappa())
```
You can then use float in the usual manner.
